require("viz.core.options")
require("viz.core.keymaps")
require("viz.plugins-setup")
require("viz.plugins.nvim-tree")
require("viz.plugins.lualine")
require("viz.plugins.telescope")
require("viz.plugins.treesitter")
require("viz.plugins.lsp")
require("viz.plugins.cmp")
require("viz.plugins.gitsigns")
require("viz.plugins.vscode")

